# Generated by Django 3.2.12 on 2022-03-22 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseModel',
            fields=[
                ('id', models.AutoField(help_text='Id主键', primary_key=True, serialize=False, verbose_name='Id主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='用例名称', max_length=200, unique=True, verbose_name='用例名称')),
                ('testcase', models.TextField(help_text='测试脚本', verbose_name='测试脚本')),
                ('desc', models.TextField(default='', help_text='用例描述', verbose_name='用例描述')),
                ('project', models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='projects.projectmodel', verbose_name='所属项目')),
            ],
        ),
    ]
