# Generated by Django 3.2.12 on 2022-03-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casemodel',
            options={'verbose_name': '用例信息', 'verbose_name_plural': '用例信息'},
        ),
        migrations.AlterModelTable(
            name='casemodel',
            table='tb_cases',
        ),
    ]
