# Generated by Django 3.2.12 on 2022-03-31 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('cases', '0002_auto_20220322_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemodel',
            name='project',
            field=models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='case', to='projects.projectmodel', verbose_name='所属项目'),
        ),
    ]
