# Generated by Django 3.2.12 on 2022-03-22 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(help_text='Id主键', primary_key=True, serialize=False, verbose_name='Id主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='报告名称', max_length=200, unique=True, verbose_name='报告名称')),
                ('log', models.TextField(default='', help_text='用例日志', verbose_name='用例日志')),
                ('screenshot', models.TextField(default='', help_text='描述', verbose_name='描述')),
                ('video', models.TextField(default='', help_text='描述', verbose_name='描述')),
                ('case', models.ForeignKey(help_text='所属用例', on_delete=django.db.models.deletion.CASCADE, to='cases.casemodel', verbose_name='所属用例')),
                ('project', models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='projects.projectmodel', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '报告信息',
                'verbose_name_plural': '报告信息',
                'db_table': 'tb_reports',
            },
        ),
    ]
