# Generated by Django 3.2.12 on 2022-03-31 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_casemodel_project'),
        ('reports', '0002_auto_20220331_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='case',
            field=models.ForeignKey(help_text='所属用例', on_delete=django.db.models.deletion.CASCADE, related_name='case', to='cases.casemodel', verbose_name='所属用例'),
        ),
    ]
